### ISSUE TITLE
MD command is shown instead of just the icon and the title

### ISSUE THREAD

**Issue by thob** [typora-community-plugin/typora-plugin-callout#1]
Am I missing something here? I can't get rid of the MD
![2024-09-29_09-56](https://github.com/user-attachments/assets/f2b593d1-8301-4911-8f81-d8f31af7a2b9)

**Comment by plylrnsdy** [comment]
You mean that you don't want to show `[!todo]`?

Typora didn't wrapped it with html and not support writing text on this line.

`plugin-callout` support writing text on this line but not support hidding `[!todo]`.

**Comment by thob** [comment]
For me the md code is a duplicate of the icon, no need for both

**Comment by thob** [comment]
see also, that's how it looks like in Obsidian, no?
![image](https://github.com/user-attachments/assets/247013ec-7e13-4ee7-ab34-64b9979039d5)
see https://forum.obsidian.md/t/all-callout-styles-for-reference/36102

**Comment by plylrnsdy** [comment]
That is a technical problem. We need to hide the text without changing Typora's editing logic. Now, I haven't a solution about it.

You can use callout like this:

```markdown
> [!TODO] Next Steps

> [!Question] How to hide callout type

> [!BUG] Can not hide callout type
```

**Comment by plylrnsdy** [comment]
That is a technical problem. We need to hide the text without changing Typora's editing logic. Now, I haven't a solution about it.

You can use callout like this:

```markdown
> [!TODO] Next Steps

> [!Question] How to hide callout type

> [!BUG] Can not hide callout type
```

**Comment by thob** [comment]
Yeah, I do understand … that's some kind of a workaround, thanks anyway 👍🏼
